[project]
name = "flathunter"
version = "0.0.1"
requires-python = ">= 3.11"
dependencies = [
    "PyYAML",
    "requests",
    "urllib3",
    "lxml",
    "coverage",
    "requests-mock",
    "Flask>=3",
    "werkzeug",
    "mock-firestore",
    "pytest-mock",
    "pytest",
    "requests-random-user-agent",
    "jsonpath-ng",
    "backoff",
    "pytz",
    "beautifulsoup4",
    "python-dotenv",
    "nodriver",
    "prompt-toolkit",
    "ruamel.yaml",
    "pyright",
    "types-beautifulsoup4==4.12.0.20241020",
    "gunicorn==23.0.0",
    "flask-api",
    "setuptools",
    "certifi",
    "jinja2",
    "cryptography",
    "pydantic",
]

[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "exceptiongroup",
    "ruff>=0.15.6",
]

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.python.org/simple"

[tool.uv.sources]
flask-api = { git = "git+https://github.com/flask-api/flask-api.git", rev = "develop" }
nodriver = { git = "https://github.com/ultrafunkamsterdam/nodriver.git", rev = "adc0da8" }

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages]
find = {namespaces = false}

[tool.ruff]
select = ["ALL"]
ignore = []
fixable = ["ALL"]
unfixable = []
exclude = [
    ".git",
    ".idea",
    ".mypy_cache",
    ".venv"
]
target-version = "py313"
